site_name: Math Problems
theme:
  name: material
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Algebra:
    - '1. Macierze i operacje': '1_Algebra/01_macierze_i_operacje.md'
    - '2. Wyznaczniki': '1_Algebra/02_wyznaczniki.md'
    - '3. Odwracanie macierzy': '1_Algebra/03_odwracanie_macierzy.md'
    - '4. Układy równań': '1_Algebra/04_uklady_rownan.md'
  - Geometria:
    - '1. Wektory': '2_Geometria/01_wektory.md'
    - '2. Proste': '2_Geometria/02_proste.md'
    - '3. Płaszczyzny': '2_Geometria/03_plaszczyzny.md'
    - '4. Prosta i płaszczyzna': '2_Geometria/04_prosta_i_plaszczyzna.md'
  - Analiza:
    - '1. Granice ciągów': '3_Analiza/01_granice_ciągów.md'
    - '2. Granice funkcji': '3_Analiza/02_granice_funkcji.md'
    - '3. Pochodne funkcji': '3_Analiza/03_pochodne_funkcji.md'
    - '4. Badanie funkcji': '3_Analiza/04_badanie_funkcji.md'
    - '5. Całki': '3_Analiza/05_całki.md'